// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_comp_APP_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Card_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Settingcard_create_hook(lv_obj_t * comp)
{
}
