// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_APP_H
#define _UI_COMP_APP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT APP
#define UI_COMP_APP_APP 0
#define _UI_COMP_APP_NUM 1
lv_obj_t * ui_APP_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
