// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_SETTINGCARD_H
#define _UI_COMP_SETTINGCARD_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Settingcard
#define UI_COMP_SETTINGCARD_SETTINGCARD 0
#define UI_COMP_SETTINGCARD_IMAGE4 1
#define UI_COMP_SETTINGCARD_LABEL12 2
#define _UI_COMP_SETTINGCARD_NUM 3
lv_obj_t * ui_Settingcard_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
