// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT APP

lv_obj_t * ui_APP_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_APP;
    cui_APP = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_APP, 50);
    lv_obj_set_height(cui_APP, 50);
    lv_obj_set_x(cui_APP, 499);
    lv_obj_set_y(cui_APP, 47);
    lv_obj_set_align(cui_APP, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_APP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_APP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_APP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_APP, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_APP_NUM);
    children[UI_COMP_APP_APP] = cui_APP;
    lv_obj_add_event_cb(cui_APP, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_APP, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_APP_create_hook(cui_APP);
    return cui_APP;
}

