// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT Settingcard

lv_obj_t * ui_Settingcard_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Settingcard;
    cui_Settingcard = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Settingcard, 220);
    lv_obj_set_height(cui_Settingcard, 70);
    lv_obj_set_x(cui_Settingcard, 0);
    lv_obj_set_y(cui_Settingcard, -80);
    lv_obj_set_align(cui_Settingcard, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_Settingcard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Image4;
    cui_Image4 = lv_img_create(cui_Settingcard);
    lv_obj_set_width(cui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Image4, -74);
    lv_obj_set_y(cui_Image4, -1);
    lv_obj_set_align(cui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label12;
    cui_Label12 = lv_label_create(cui_Settingcard);
    lv_obj_set_width(cui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label12, -1);
    lv_obj_set_y(cui_Label12, -2);
    lv_obj_set_align(cui_Label12, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(cui_Label12, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SETTINGCARD_NUM);
    children[UI_COMP_SETTINGCARD_SETTINGCARD] = cui_Settingcard;
    children[UI_COMP_SETTINGCARD_IMAGE4] = cui_Image4;
    children[UI_COMP_SETTINGCARD_LABEL12] = cui_Label12;
    lv_obj_add_event_cb(cui_Settingcard, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Settingcard, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Settingcard_create_hook(cui_Settingcard);
    return cui_Settingcard;
}

