// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../Inc/ui_App_Calendat_Page.h"
#include "../Inc/ui_Application_Page.h"

lv_obj_t * ui_App_Calendat_Page = NULL;
Page_t Page_App_Calendat = {ui_App_Calendat_Page_screen_init, ui_App_Calendat_Page_deinit, &ui_App_Calendat_Page};
lv_obj_t * ui_Calendar1 = NULL;

// event funtions
static void ui_event_Calendar1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Page_Back(LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0);
    }
}

// build funtions

void ui_App_Calendat_Page_screen_init(void)
{
    ui_App_Calendat_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_App_Calendat_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_App_Calendat_Page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calendar1 = lv_calendar_create(ui_App_Calendat_Page);
    lv_calendar_set_today_date(ui_Calendar1, 2026, 6, 20);
    lv_calendar_set_showed_date(ui_Calendar1, 2026, 6);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 240);
    lv_obj_set_height(ui_Calendar1, 280);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Calendar1, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    lv_obj_add_event_cb(ui_Calendar1, ui_event_Calendar1, LV_EVENT_ALL, NULL);

}

void ui_App_Calendat_Page_deinit(void)
{
    ui_App_Calendat_Page = NULL;
    ui_Calendar1 = NULL;
}
