// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../Inc/ui_Application_Page.h"
#include "../Inc/ui_Application1_Page.h"
#include "../Inc/ui_App_Calendat_Page.h"
#include "../Inc/ui_App_CalcPage.h"
#include "../Inc/ui_App_HRPage.h"
#include "../Inc/ui_App_CompassPage.h"
lv_obj_t * ui_Application_Page = NULL;
Page_t Page_Application = {ui_Application_Page_screen_init, ui_Application_Page_deinit, &ui_Application_Page};
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Panel14 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Panel15 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Scrolldots1 = NULL;
lv_obj_t * ui_d1 = NULL;
lv_obj_t * ui_d2 = NULL;
/*图片*/
LV_IMG_DECLARE(ui_img_298121455);    // assets/计算器.png
LV_IMG_DECLARE(ui_img_272253901);    // assets/指南针.png
LV_IMG_DECLARE(ui_img_2138131786);    // assets/日历.png
LV_IMG_DECLARE(ui_img_1389843189);    // assets/心率.png
// event funtions
static void ui_event_Application_Page(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Page_Back(LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        Page_Load(&Page_Application1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0);
    }
}
//日历
static void ui_event_Image11(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Page_Load(&Page_App_Calendat, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0);
    }
}
//计算器
static void ui_event_Image6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    
    if(event_code == LV_EVENT_CLICKED) {
        Page_Load(&Page_App_Calc, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0);
    }
}
//指南针
static void ui_event_Image10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    
    if(event_code == LV_EVENT_CLICKED) {
        Page_Load(&Page_App_Compass, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0);
    }
}
//心率
static void ui_event_Image12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    
    if(event_code == LV_EVENT_CLICKED) {
        Page_Load(&Page_App_HR, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0);
    }
}

// build funtions

void ui_Application_Page_screen_init(void)
{
    ui_Application_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Application_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Application_Page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Application_Page);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, -115);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "APP");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Application_Page);
    lv_obj_set_width(ui_Panel10, 200);
    lv_obj_set_height(ui_Panel10, 200);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel10, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel11, 80);
    lv_obj_set_height(ui_Panel11, 80);
    lv_obj_set_x(ui_Panel11, -48);
    lv_obj_set_y(ui_Panel11, -49);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x9BA0AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Panel11);
    lv_obj_set_width(ui_Label22, 75);
    lv_obj_set_height(ui_Label22, 15);
    lv_obj_set_x(ui_Label22, 0);
    lv_obj_set_y(ui_Label22, 26);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Calculator");

    ui_Image6 = lv_label_create(ui_Panel11);
    lv_label_set_text(ui_Image6, "Calc");
    lv_obj_set_style_text_font(ui_Image6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Image6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_x(ui_Image6, 0);
    lv_obj_set_y(ui_Image6, -5);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel13 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel13, 80);
    lv_obj_set_height(ui_Panel13, 80);
    lv_obj_set_x(ui_Panel13, -48);
    lv_obj_set_y(ui_Panel13, -49);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label25, 75);
    lv_obj_set_height(ui_Label25, 15);
    lv_obj_set_x(ui_Label25, 5);
    lv_obj_set_y(ui_Label25, 26);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Compass");

    ui_Image10 = lv_label_create(ui_Panel13);
    lv_label_set_text(ui_Image10, "Comp");
    lv_obj_set_style_text_font(ui_Image10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Image10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_x(ui_Image10, 0);
    lv_obj_set_y(ui_Image10, -5);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel14 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel14, 80);
    lv_obj_set_height(ui_Panel14, 80);
    lv_obj_set_x(ui_Panel14, -48);
    lv_obj_set_y(ui_Panel14, -49);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label26, 75);
    lv_obj_set_height(ui_Label26, 15);
    lv_obj_set_x(ui_Label26, 5);
    lv_obj_set_y(ui_Label26, 26);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Calendar");

    ui_Image11 = lv_label_create(ui_Panel14);
    lv_label_set_text(ui_Image11, "Cal");
    lv_obj_set_style_text_font(ui_Image11, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Image11, lv_color_hex(0x5AC8FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_x(ui_Image11, 0);
    lv_obj_set_y(ui_Image11, -5);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel15 = lv_obj_create(ui_Panel10);
    lv_obj_set_width(ui_Panel15, 80);
    lv_obj_set_height(ui_Panel15, 80);
    lv_obj_set_x(ui_Panel15, -48);
    lv_obj_set_y(ui_Panel15, -49);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_Label27, 75);
    lv_obj_set_height(ui_Label27, 15);
    lv_obj_set_x(ui_Label27, 2);
    lv_obj_set_y(ui_Label27, 26);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "HeartRate");

    ui_Image12 = lv_label_create(ui_Panel15);
    lv_label_set_text(ui_Image12, "HR");
    lv_obj_set_style_text_font(ui_Image12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Image12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_x(ui_Image12, 0);
    lv_obj_set_y(ui_Image12, -5);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Scrolldots1 = lv_obj_create(ui_Application_Page);
    lv_obj_set_width(ui_Scrolldots1, 40);
    lv_obj_set_height(ui_Scrolldots1, 12);
    lv_obj_set_x(ui_Scrolldots1, 0);
    lv_obj_set_y(ui_Scrolldots1, -8);
    lv_obj_set_align(ui_Scrolldots1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Scrolldots1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Scrolldots1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Scrolldots1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Scrolldots1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Scrolldots1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_d1 = lv_obj_create(ui_Scrolldots1);
    lv_obj_set_width(ui_d1, 8);
    lv_obj_set_height(ui_d1, 8);
    lv_obj_set_align(ui_d1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_d1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_d1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_d1, lv_color_hex(0xB4B6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_d1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_d2 = lv_obj_create(ui_Scrolldots1);
    lv_obj_set_width(ui_d2, 4);
    lv_obj_set_height(ui_d2, 4);
    lv_obj_set_x(ui_d2, 15);
    lv_obj_set_y(ui_d2, 0);
    lv_obj_set_align(ui_d2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_d2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_d2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_d2, lv_color_hex(0xB4B6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_d2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel14, ui_event_Image11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel11, ui_event_Image6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel13, ui_event_Image10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel15, ui_event_Image12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Application_Page, ui_event_Application_Page, LV_EVENT_ALL, NULL);
}

void ui_Application_Page_deinit(void)
{
    ui_Application_Page = NULL;
    ui_Label11 = NULL;
    ui_Panel10 = NULL;
    ui_Panel11 = NULL;
    ui_Label22 = NULL;
    ui_Image6 = NULL;
    ui_Panel13 = NULL;
    ui_Label25 = NULL;
    ui_Image10 = NULL;
    ui_Panel14 = NULL;
    ui_Label26 = NULL;
    ui_Image11 = NULL;
    ui_Panel15 = NULL;
    ui_Label27 = NULL;
    ui_Image12 = NULL;
    ui_Scrolldots1 = NULL;
    ui_d1 = NULL;
    ui_d2 = NULL;
}
