// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../Inc/ui_Application1_Page.h"
#include "../Inc/ui_Application_Page.h"

lv_obj_t * ui_Application1_Page = NULL;
Page_t Page_Application1 = {ui_Application1_Page_screen_init, ui_Application1_Page_deinit, &ui_Application1_Page};
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Scrolldots2 = NULL;
lv_obj_t * ui_d7 = NULL;
lv_obj_t * ui_d8 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Panel16 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Panel18 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Panel19 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Image15 = NULL;
/*图片*/
LV_IMG_DECLARE(ui_img_2048_png);    // assets/2048.png
LV_IMG_DECLARE(ui_img_1178775628);    // assets/手电筒_开.png
// event funtions
void ui_event_Application1_Page(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Page_Back(LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0);
    }
}
//灯
static void ui_event_Image9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    
    if(event_code == LV_EVENT_CLICKED) {
        //Page_Load(&, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0);
    }
}
//2048游戏
static void ui_event_Image13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    
    if(event_code == LV_EVENT_CLICKED) {
        //Page_Load(&, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0);
    }
}
// build funtions

void ui_Application1_Page_screen_init(void)
{
    ui_Application1_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Application1_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Application1_Page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Application1_Page);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, -115);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "APP");
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scrolldots2 = lv_obj_create(ui_Application1_Page);
    lv_obj_set_width(ui_Scrolldots2, 40);
    lv_obj_set_height(ui_Scrolldots2, 12);
    lv_obj_set_x(ui_Scrolldots2, 0);
    lv_obj_set_y(ui_Scrolldots2, -8);
    lv_obj_set_align(ui_Scrolldots2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Scrolldots2, LV_FLEX_FLOW_ROW_REVERSE);
    lv_obj_set_flex_align(ui_Scrolldots2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Scrolldots2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Scrolldots2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Scrolldots2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_d7 = lv_obj_create(ui_Scrolldots2);
    lv_obj_set_width(ui_d7, 8);
    lv_obj_set_height(ui_d7, 8);
    lv_obj_set_align(ui_d7, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_d7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_d7, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_d7, lv_color_hex(0xB4B6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_d7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_d8 = lv_obj_create(ui_Scrolldots2);
    lv_obj_set_width(ui_d8, 4);
    lv_obj_set_height(ui_d8, 4);
    lv_obj_set_x(ui_d8, 15);
    lv_obj_set_y(ui_d8, 0);
    lv_obj_set_align(ui_d8, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_d8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_d8, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_d8, lv_color_hex(0xB4B6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_d8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_Application1_Page);
    lv_obj_set_width(ui_Panel12, 200);
    lv_obj_set_height(ui_Panel12, 200);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel12, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_Panel12);
    lv_obj_set_width(ui_Panel16, 80);
    lv_obj_set_height(ui_Panel16, 80);
    lv_obj_set_x(ui_Panel16, -48);
    lv_obj_set_y(ui_Panel16, -49);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x9BA0AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_Label28, 39);
    lv_obj_set_height(ui_Label28, 15);
    lv_obj_set_x(ui_Label28, -2);
    lv_obj_set_y(ui_Label28, 29);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Light");

    ui_Image9 = lv_label_create(ui_Panel16);
    lv_label_set_text(ui_Image9, "Light");
    lv_obj_set_style_text_font(ui_Image9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Image9, lv_color_hex(0xBEB910), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_x(ui_Image9, 0);
    lv_obj_set_y(ui_Image9, -5);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel17 = lv_obj_create(ui_Panel12);
    lv_obj_set_width(ui_Panel17, 80);
    lv_obj_set_height(ui_Panel17, 80);
    lv_obj_set_x(ui_Panel17, -48);
    lv_obj_set_y(ui_Panel17, -49);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel17, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label29, 40);
    lv_obj_set_height(ui_Label29, 15);
    lv_obj_set_x(ui_Label29, 1);
    lv_obj_set_y(ui_Label29, 29);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "2048");

    ui_Image13 = lv_label_create(ui_Panel17);
    lv_label_set_text(ui_Image13, "2048");
    lv_obj_set_style_text_font(ui_Image13, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Image13, lv_color_hex(0x2094FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_x(ui_Image13, 0);
    lv_obj_set_y(ui_Image13, -5);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel18 = lv_obj_create(ui_Panel12);
    lv_obj_set_width(ui_Panel18, 80);
    lv_obj_set_height(ui_Panel18, 80);
    lv_obj_set_x(ui_Panel18, -48);
    lv_obj_set_y(ui_Panel18, -49);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel18, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label30, 75);
    lv_obj_set_height(ui_Label30, 15);
    lv_obj_set_x(ui_Label30, 5);
    lv_obj_set_y(ui_Label30, 26);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);

    ui_Image14 = lv_img_create(ui_Panel18);
    lv_obj_set_width(ui_Image14, 50);
    lv_obj_set_height(ui_Image14, 50);
    lv_obj_set_x(ui_Image14, 0);
    lv_obj_set_y(ui_Image14, -5);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel19 = lv_obj_create(ui_Panel12);
    lv_obj_set_width(ui_Panel19, 80);
    lv_obj_set_height(ui_Panel19, 80);
    lv_obj_set_x(ui_Panel19, -48);
    lv_obj_set_y(ui_Panel19, -49);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel19, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Panel19);
    lv_obj_set_width(ui_Label31, 75);
    lv_obj_set_height(ui_Label31, 15);
    lv_obj_set_x(ui_Label31, 2);
    lv_obj_set_y(ui_Label31, 26);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);

    ui_Image15 = lv_img_create(ui_Panel19);
    lv_obj_set_width(ui_Image15, 50);
    lv_obj_set_height(ui_Image15, 50);
    lv_obj_set_x(ui_Image15, 0);
    lv_obj_set_y(ui_Image15, -5);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    /*ui_Image15 和 ui_Image14暂时隐藏*/
    lv_obj_add_event_cb(ui_Image9, ui_event_Image9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image13, ui_event_Image13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Application1_Page, ui_event_Application1_Page, LV_EVENT_ALL, NULL);

}

void ui_Application1_Page_deinit(void)
{
    ui_Application1_Page = NULL;
    ui_Label23 = NULL;
    ui_Scrolldots2 = NULL;
    ui_d7 = NULL;
    ui_d8 = NULL;
    ui_Panel12 = NULL;
    ui_Panel16 = NULL;
    ui_Label28 = NULL;
    ui_Image9 = NULL;
    ui_Panel17 = NULL;
    ui_Label29 = NULL;
    ui_Image13 = NULL;
    ui_Panel18 = NULL;
    ui_Label30 = NULL;
    ui_Image14 = NULL;
    ui_Panel19 = NULL;
    ui_Label31 = NULL;
    ui_Image15 = NULL;
}
