// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../Inc/ui_Charging_Page.h"
#include "HwDataAccess.h"
#include <stdio.h>
lv_obj_t * ui_Charging_Page = NULL;
Page_t Page_Charging = {ui_Charging_Page_screen_init, ui_Charging_Page_deinit, &ui_Charging_Page};
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_battery = NULL;
lv_obj_t * ui_Label33 = NULL;
static lv_timer_t *ui_ChargPageTimer = NULL;
/**
  * @brief  Charging page timer callback (2s period)
  * @param  timer: LVGL timer
  * @retval None
  */
static void ChargPage_timer_cb(lv_timer_t *timer)
{
  char buf[16];
  uint8_t bat = HWInterface.Power.power_remain;
  sprintf(buf, "%d%%", bat);
  lv_label_set_text(ui_battery, buf);
  lv_arc_set_value(ui_Arc1, bat);
}

// event funtions
static void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
       Page_Back(LV_SCR_LOAD_ANIM_FADE_ON, 250, 0);
    }
}

// build funtions

void ui_Charging_Page_screen_init(void)
{
    ui_Charging_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Charging_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Charging_Page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_Charging_Page);
    lv_obj_set_width(ui_Button4, 200);
    lv_obj_set_height(ui_Button4, 50);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 108);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x9BA0AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "OFF");
    lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_Charging_Page);
    lv_obj_set_width(ui_Arc1, 100);
    lv_obj_set_height(ui_Arc1, 100);
    lv_obj_set_x(ui_Arc1, 0);
    lv_obj_set_y(ui_Arc1, -40);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);
    lv_arc_set_bg_angles(ui_Arc1, 0, 360);
    lv_arc_set_rotation(ui_Arc1, 270);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x04DE71), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_battery = lv_label_create(ui_Arc1);
    lv_obj_set_width(ui_battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_battery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_battery, "50%");
    lv_obj_set_style_text_font(ui_battery, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_Charging_Page);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, 0);
    lv_obj_set_y(ui_Label33, 30);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "Charging...");
    lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
  // Timer for battery update
    ui_ChargPageTimer = lv_timer_create(ChargPage_timer_cb, 2000, NULL);
}

void ui_Charging_Page_deinit(void)
{
    //删除定时器
    if(ui_ChargPageTimer)
    {
        lv_timer_del(ui_ChargPageTimer);
        ui_ChargPageTimer = NULL;
    }
    //页面对象
    ui_Charging_Page = NULL;
    ui_Button4 = NULL;
    ui_Label32 = NULL;
    ui_Arc1 = NULL;
    ui_battery = NULL;
    ui_Label33 = NULL;

}
