// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../Inc/ui_Setting__SystemUpdates_Page.h"
#include "../Inc/ui_Setting_Page.h"
#include "../Inc/ui_Setting__SystemUpdates_Poweroff_Page.h"
#include "HWDataAccess.h"
#include <stdio.h>
lv_obj_t * ui_Setting__SystemUpdates_Page = NULL;
Page_t Page_Setting_SystemUpdates = {ui_Setting__SystemUpdates_Page_screen_init, ui_Setting__SystemUpdates_Page_deinit, &ui_Setting__SystemUpdates_Page};
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Settingcard4 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Settingcard14 = NULL;
lv_obj_t * ui_Label35 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Time6 = NULL;

static lv_timer_t *ui_Setting_SystemUpdates_PageTimer = NULL;
static uint8_t ui_TimeHourValue = 12;
static uint8_t ui_TimeMinuteValue = 0;
/**
  * @brief   Setting_SystemUpdates timer callback (500ms period)
  * @param  timer: LVGL timer
  * @retval None
  */
static void Setting_SystemUpdates_timer_cb(lv_timer_t *timer)
{
  char buf[20]; 
  // Time update (every 500ms)
  HW_DateTimeTypeDef DateTime;
  HWInterface.RealTimeClock.GetTimeDate(&DateTime);
  
  if(ui_TimeHourValue != DateTime.Hours||ui_TimeMinuteValue != DateTime.Minutes)
  {
    ui_TimeHourValue = DateTime.Hours;
    ui_TimeMinuteValue = DateTime.Minutes;
    sprintf(buf, "%02d:%02d", ui_TimeHourValue,ui_TimeMinuteValue);
    lv_label_set_text(ui_Time6, buf);
  }
}

// event funtions
void ui_event_Panel6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Page_Back(LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0);
    }
}
//POWER OFF
void ui_event_Settingcard4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Page_Load(&Page_Setting_SystemUpdates_Poweroff, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0);
    }
}

//FIRMWARE UPDATE（未实现）
void ui_event_Settingcard14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // Page_Load(&Page_Setting_SystemUpdates_FirmwareUpdate, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0);
    }
}

// build funtions

void ui_Setting__SystemUpdates_Page_screen_init(void)
{
    ui_Setting__SystemUpdates_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Setting__SystemUpdates_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting__SystemUpdates_Page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Setting__SystemUpdates_Page);
    lv_obj_set_width(ui_Panel6, 240);
    lv_obj_set_height(ui_Panel6, 250);
    lv_obj_set_x(ui_Panel6, 1);
    lv_obj_set_y(ui_Panel6, 15);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel6, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_Panel6, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settingcard4 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Settingcard4, 220);
    lv_obj_set_height(ui_Settingcard4, 70);
    lv_obj_set_x(ui_Settingcard4, 0);
    lv_obj_set_y(ui_Settingcard4, -80);
    lv_obj_set_align(ui_Settingcard4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Settingcard4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Settingcard4);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label16, "Power Off");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_label_create(ui_Settingcard4);
    lv_label_set_text(ui_Image8, ">");
    lv_obj_set_style_text_font(ui_Image8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Image8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_align(ui_Image8, LV_ALIGN_RIGHT_MID);

    ui_Settingcard14 = lv_obj_create(ui_Panel6);
    lv_obj_set_width(ui_Settingcard14, 220);
    lv_obj_set_height(ui_Settingcard14, 70);
    lv_obj_set_x(ui_Settingcard14, 0);
    lv_obj_set_y(ui_Settingcard14, -80);
    lv_obj_set_align(ui_Settingcard14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Settingcard14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label35 = lv_label_create(ui_Settingcard14);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label35, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label35, "Firmware\nUpdate");
    lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image17 = lv_label_create(ui_Settingcard14);
    lv_label_set_text(ui_Image17, ">");
    lv_obj_set_style_text_font(ui_Image17, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Image17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_align(ui_Image17, LV_ALIGN_RIGHT_MID);

    ui_Label19 = lv_label_create(ui_Setting__SystemUpdates_Page);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 5);
    lv_obj_set_y(ui_Label19, 6);
    lv_label_set_text(ui_Label19, " System&Updates");
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time6 = lv_label_create(ui_Setting__SystemUpdates_Page);
    lv_obj_set_width(ui_Time6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time6, -5);
    lv_obj_set_y(ui_Time6, 6);
    lv_obj_set_align(ui_Time6, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Time6, "10:00");
    lv_obj_set_style_text_font(ui_Time6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Settingcard4, ui_event_Settingcard4, LV_EVENT_ALL, NULL);
    //lv_obj_add_event_cb(ui_Settingcard14, ui_event_Settingcard14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel6, ui_event_Panel6, LV_EVENT_ALL, NULL);

    ui_Setting_SystemUpdates_PageTimer = lv_timer_create(Setting_SystemUpdates_timer_cb, 500, NULL);
}

void ui_Setting__SystemUpdates_Page_deinit(void)
{
    if(ui_Setting_SystemUpdates_PageTimer != NULL)
    {
        lv_timer_del(ui_Setting_SystemUpdates_PageTimer);
        ui_Setting_SystemUpdates_PageTimer = NULL;
    }
    ui_Setting__SystemUpdates_Page = NULL;
    ui_Panel6 = NULL;
    ui_Settingcard4 = NULL;
    ui_Label16 = NULL;
    ui_Image8 = NULL;
    ui_Settingcard14 = NULL;
    ui_Label35 = NULL;
    ui_Image17 = NULL;
    ui_Label19 = NULL;
    ui_Time6 = NULL;
}
