// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../Inc/ui_Setting_About_Page.h"
#include "../Inc/ui_Setting_Page.h"
#include "HWDataAccess.h"
#include <stdio.h>
lv_obj_t * ui_Setting_About_Page = NULL;
Page_t Page_Setting_About = {ui_Setting_About_Page_screen_init, ui_Setting_About_Page_deinit, &ui_Setting_About_Page};
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Settingcard7 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Settingcard11 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Settingcard12 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Settingcard13 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Time7 = NULL;

static lv_timer_t *ui_Setting_About_PageTimer = NULL;
static uint8_t ui_TimeHourValue = 12;
static uint8_t ui_TimeMinuteValue = 0;
/**
  * @brief   Setting_About timer callback (500ms period)
  * @param  timer: LVGL timer
  * @retval None
  */
static void Setting_About_Page_timer_cb(lv_timer_t *timer)
{
  char buf[20]; 
  // Time update (every 500ms)
  HW_DateTimeTypeDef DateTime;
  HWInterface.RealTimeClock.GetTimeDate(&DateTime);
  
  if(ui_TimeHourValue != DateTime.Hours||ui_TimeMinuteValue != DateTime.Minutes)
  {
    ui_TimeHourValue = DateTime.Hours;
    ui_TimeMinuteValue = DateTime.Minutes;
    sprintf(buf, "%02d:%02d", ui_TimeHourValue,ui_TimeMinuteValue);
    lv_label_set_text(ui_Time7, buf);
  }
}
// event funtions
void ui_event_Panel8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Page_Back(LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0);
    }
}

// build funtions

void ui_Setting_About_Page_screen_init(void)
{
    ui_Setting_About_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Setting_About_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_About_Page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Setting_About_Page);
    lv_obj_set_width(ui_Panel8, 240);
    lv_obj_set_height(ui_Panel8, 250);
    lv_obj_set_x(ui_Panel8, 1);
    lv_obj_set_y(ui_Panel8, 15);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel8, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel8, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_scroll_dir(ui_Panel8, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settingcard7 = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_Settingcard7, 220);
    lv_obj_set_height(ui_Settingcard7, 70);
    lv_obj_set_x(ui_Settingcard7, 0);
    lv_obj_set_y(ui_Settingcard7, -80);
    lv_obj_set_align(ui_Settingcard7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Settingcard7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settingcard7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settingcard7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Settingcard7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Settingcard7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Settingcard7);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label1, "Device");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Settingcard7);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 15);
    lv_obj_set_align(ui_Label5, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label5, "OV watch");

    ui_Settingcard11 = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_Settingcard11, 220);
    lv_obj_set_height(ui_Settingcard11, 70);
    lv_obj_set_x(ui_Settingcard11, 0);
    lv_obj_set_y(ui_Settingcard11, -80);
    lv_obj_set_align(ui_Settingcard11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Settingcard11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settingcard11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settingcard11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Settingcard11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Settingcard11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Settingcard11);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label6, "Model Number");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Settingcard11);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 15);
    lv_obj_set_align(ui_Label2, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label2, "BOT-WB00");

    ui_Settingcard12 = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_Settingcard12, 220);
    lv_obj_set_height(ui_Settingcard12, 70);
    lv_obj_set_x(ui_Settingcard12, 0);
    lv_obj_set_y(ui_Settingcard12, -80);
    lv_obj_set_align(ui_Settingcard12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Settingcard12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settingcard12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settingcard12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Settingcard12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Settingcard12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Settingcard12);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label7, "Version");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Settingcard12);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 15);
    lv_obj_set_align(ui_Label8, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_Label8, "1.00");

    ui_Settingcard13 = lv_obj_create(ui_Panel8);
    lv_obj_set_width(ui_Settingcard13, 220);
    lv_obj_set_height(ui_Settingcard13, 20);
    lv_obj_set_x(ui_Settingcard13, 0);
    lv_obj_set_y(ui_Settingcard13, -80);
    lv_obj_set_align(ui_Settingcard13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Settingcard13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settingcard13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settingcard13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Settingcard13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Settingcard13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Setting_About_Page);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 5);
    lv_obj_set_y(ui_Label4, 6);
    lv_label_set_text(ui_Label4, "About");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time7 = lv_label_create(ui_Setting_About_Page);
    lv_obj_set_width(ui_Time7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time7, -5);
    lv_obj_set_y(ui_Time7, 6);
    lv_obj_set_align(ui_Time7, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Time7, "10:00");
    lv_obj_set_style_text_font(ui_Time7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Panel8, ui_event_Panel8, LV_EVENT_ALL, NULL);

    ui_Setting_About_PageTimer = lv_timer_create(Setting_About_Page_timer_cb, 500, NULL);
}

void ui_Setting_About_Page_deinit(void)
{
    if(ui_Setting_About_PageTimer != NULL)
    {
        lv_timer_del(ui_Setting_About_PageTimer);
        ui_Setting_About_PageTimer = NULL;
    }
    ui_Setting_About_Page = NULL;
    ui_Panel8 = NULL;
    ui_Settingcard7 = NULL;
    ui_Label1 = NULL;
    ui_Label5 = NULL;
    ui_Settingcard11 = NULL;
    ui_Label6 = NULL;
    ui_Label2 = NULL;
    ui_Settingcard12 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_Settingcard13 = NULL;
    ui_Label4 = NULL;
    ui_Time7 = NULL;
}
