// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../Inc/ui_Setting_Barttery_Saver_Page.h"
#include "../Inc/ui_Setting_Page.h"
#include "HWDataAccess.h"
#include <stdio.h>
lv_obj_t * ui_Setting_Barttery_Saver_Page = NULL;
Page_t Page_Setting_Battery_Saver = {ui_Setting_Barttery_Saver_Page_screen_init, ui_Setting_Barttery_Saver_Page_deinit, &ui_Setting_Barttery_Saver_Page};
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Settingcard9 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Time5 = NULL;

static lv_timer_t *ui_Setting_Barttery_Saver_PageTimer = NULL;
static uint8_t ui_TimeHourValue = 12;
static uint8_t ui_TimeMinuteValue = 0;
/**
  * @brief   Setting_Barttery_Saver timer callback (500ms period)
  * @param  timer: LVGL timer
  * @retval None
  */
static void Setting_Barttery_Saver_Page_timer_cb(lv_timer_t *timer)
{
  char buf[20]; 
  // Time update (every 500ms)
  HW_DateTimeTypeDef DateTime;
  HWInterface.RealTimeClock.GetTimeDate(&DateTime);
  
  if(ui_TimeHourValue != DateTime.Hours||ui_TimeMinuteValue != DateTime.Minutes)
  {
    ui_TimeHourValue = DateTime.Hours;
    ui_TimeMinuteValue = DateTime.Minutes;
    sprintf(buf, "%02d:%02d", ui_TimeHourValue,ui_TimeMinuteValue);
    lv_label_set_text(ui_Time5, buf);
  }
}

// event funtions
void ui_event_Panel5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Page_Back(LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0);
    }
}
//省电模式（未实现）
void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        //(e);
    }
}

// build funtions

void ui_Setting_Barttery_Saver_Page_screen_init(void)
{
    ui_Setting_Barttery_Saver_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Setting_Barttery_Saver_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_Barttery_Saver_Page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Setting_Barttery_Saver_Page);
    lv_obj_set_width(ui_Panel5, 240);
    lv_obj_set_height(ui_Panel5, 250);
    lv_obj_set_x(ui_Panel5, 1);
    lv_obj_set_y(ui_Panel5, 15);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_Panel5, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settingcard9 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Settingcard9, 220);
    lv_obj_set_height(ui_Settingcard9, 70);
    lv_obj_set_x(ui_Settingcard9, 0);
    lv_obj_set_y(ui_Settingcard9, -80);
    lv_obj_set_align(ui_Settingcard9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Settingcard9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Settingcard9);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label20, "Battery-Saver\n        Mode(Undone)");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Settingcard9);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_RIGHT_MID);

    ui_Label21 = lv_label_create(ui_Setting_Barttery_Saver_Page);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 5);
    lv_obj_set_y(ui_Label21, 6);
    lv_label_set_text(ui_Label21, "Battery-Saver Mode");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time5 = lv_label_create(ui_Setting_Barttery_Saver_Page);
    lv_obj_set_width(ui_Time5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time5, -5);
    lv_obj_set_y(ui_Time5, 6);
    lv_obj_set_align(ui_Time5, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Time5, "10:00");
    lv_obj_set_style_text_font(ui_Time5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel5, ui_event_Panel5, LV_EVENT_ALL, NULL);

    ui_Setting_Barttery_Saver_PageTimer = lv_timer_create(Setting_Barttery_Saver_Page_timer_cb, 500, NULL);
}

void ui_Setting_Barttery_Saver_Page_deinit(void)
{
    if(ui_Setting_Barttery_Saver_PageTimer)
    {
        lv_timer_del(ui_Setting_Barttery_Saver_PageTimer);
        ui_Setting_Barttery_Saver_PageTimer = NULL;
    }
    ui_Setting_Barttery_Saver_Page = NULL;
    ui_Panel5 = NULL;
    ui_Settingcard9 = NULL;
    ui_Label20 = NULL;
    ui_Switch2 = NULL;
    ui_Label21 = NULL;
    ui_Time5 = NULL;
}
