// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../Inc/ui_Setting_Page.h"
#include "../Inc/ui_Menu_Page.h"
#include "../Inc/ui_Setting_Dis_Bri_Page.h"
#include "../Inc/ui_Setting_Barttery_Saver_Page.h"
#include "../Inc/ui_Setting__SystemUpdates_Page.h"
#include "../Inc/ui_Setting_About_Page.h"
#include "HWDataAccess.h"
#include "stdio.h"
lv_obj_t * ui_Setting_Page = NULL;
Page_t Page_Setting = {ui_Setting_Page_screen_init, ui_Setting_Page_deinit, &ui_Setting_Page};
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Settingcard = NULL;
lv_obj_t * ui_Settingcard1 = NULL;
lv_obj_t * ui_Settingcard2 = NULL;
lv_obj_t * ui_Settingcard3 = NULL;
lv_obj_t * ui_Label10 = NULL;
static lv_obj_t * ui_TimeHourLabel = NULL;
static lv_obj_t * ui_TimeColonLabel = NULL;
static lv_obj_t * ui_TimeMinuteLabel = NULL;
static lv_timer_t *ui_Setting_PageTimer = NULL;
static uint8_t ui_TimeHourValue = 12;
static uint8_t ui_TimeMinuteValue = 0;
/*图片*/
LV_IMG_DECLARE(ui_img_783175834);    // assets/设置-显示与亮度.png
LV_IMG_DECLARE(ui_img_1402427003);    // assets/状态-省电模式.png
LV_IMG_DECLARE(ui_img_1177623285);    // assets/系统.png
LV_IMG_DECLARE(ui_img_2092788291);    // assets/关于我们.png
/**
  * @brief   Setting page timer callback (500ms period)
  * @param  timer: LVGL timer
  * @retval None
  */
static void Setting_Page_timer_cb(lv_timer_t *timer)
{
  char buf[20]; 
  // Time update (every 500ms)
  HW_DateTimeTypeDef DateTime;
  HWInterface.RealTimeClock.GetTimeDate(&DateTime);
  
  if(ui_TimeHourValue != DateTime.Hours)
  {
    ui_TimeHourValue = DateTime.Hours;
    sprintf(buf, "%02d", ui_TimeHourValue);
    lv_label_set_text(ui_TimeHourLabel, buf);
  }
  
  if(ui_TimeMinuteValue != DateTime.Minutes)
  {
    ui_TimeMinuteValue = DateTime.Minutes;
    sprintf(buf, "%02d", ui_TimeMinuteValue);
    lv_label_set_text(ui_TimeMinuteLabel, buf);
  }
}

// event funtions
void ui_event_Panel3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Page_Back(LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0);
    }
}

void ui_event_Settingcard_Settingcard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Page_Load(&Page_Setting_Dis_Bri, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0);
    }
}

void ui_event_Settingcard1_Settingcard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Page_Load(&Page_Setting_Battery_Saver, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0);
    }
}

void ui_event_Settingcard2_Settingcard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Page_Load(&Page_Setting_SystemUpdates, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0);
    }
}

void ui_event_Settingcard3_Settingcard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Page_Load(&Page_Setting_About, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0);
    }
}

// build funtions

void ui_Setting_Page_screen_init(void)
{
    ui_Setting_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Setting_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_Page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Setting_Page);
    lv_obj_set_width(ui_Panel3, 240);
    lv_obj_set_height(ui_Panel3, 250);
    lv_obj_set_x(ui_Panel3, 1);
    lv_obj_set_y(ui_Panel3, 15);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_scroll_dir(ui_Panel3, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settingcard = ui_Settingcard_create(ui_Panel3);
    lv_obj_set_x(ui_Settingcard, 0);
    lv_obj_set_y(ui_Settingcard, -80);

    lv_img_set_src(ui_comp_get_child(ui_Settingcard, UI_COMP_SETTINGCARD_IMAGE4), &ui_img_783175834);

    lv_obj_set_x(ui_comp_get_child(ui_Settingcard, UI_COMP_SETTINGCARD_LABEL12), 30);
    lv_obj_set_y(ui_comp_get_child(ui_Settingcard, UI_COMP_SETTINGCARD_LABEL12), 0);
    lv_label_set_text(ui_comp_get_child(ui_Settingcard, UI_COMP_SETTINGCARD_LABEL12),
                      "   Display \n         &\nBrightness");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_Settingcard, UI_COMP_SETTINGCARD_LABEL12), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settingcard1 = ui_Settingcard_create(ui_Panel3);
    lv_obj_set_x(ui_Settingcard1, 0);
    lv_obj_set_y(ui_Settingcard1, -80);

    lv_img_set_src(ui_comp_get_child(ui_Settingcard1, UI_COMP_SETTINGCARD_IMAGE4), &ui_img_1402427003);

    lv_obj_set_x(ui_comp_get_child(ui_Settingcard1, UI_COMP_SETTINGCARD_LABEL12), 30);
    lv_obj_set_y(ui_comp_get_child(ui_Settingcard1, UI_COMP_SETTINGCARD_LABEL12), 0);
    lv_label_set_text(ui_comp_get_child(ui_Settingcard1, UI_COMP_SETTINGCARD_LABEL12), "Battery-Saver\n        Mode");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_Settingcard1, UI_COMP_SETTINGCARD_LABEL12), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settingcard2 = ui_Settingcard_create(ui_Panel3);
    lv_obj_set_x(ui_Settingcard2, 0);
    lv_obj_set_y(ui_Settingcard2, -80);

    lv_img_set_src(ui_comp_get_child(ui_Settingcard2, UI_COMP_SETTINGCARD_IMAGE4), &ui_img_1177623285);

    lv_obj_set_x(ui_comp_get_child(ui_Settingcard2, UI_COMP_SETTINGCARD_LABEL12), 30);
    lv_obj_set_y(ui_comp_get_child(ui_Settingcard2, UI_COMP_SETTINGCARD_LABEL12), 0);
    lv_label_set_text(ui_comp_get_child(ui_Settingcard2, UI_COMP_SETTINGCARD_LABEL12), " System\n      &\nUpdates");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_Settingcard2, UI_COMP_SETTINGCARD_LABEL12), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settingcard3 = ui_Settingcard_create(ui_Panel3);
    lv_obj_set_x(ui_Settingcard3, 0);
    lv_obj_set_y(ui_Settingcard3, -80);

    lv_img_set_src(ui_comp_get_child(ui_Settingcard3, UI_COMP_SETTINGCARD_IMAGE4), &ui_img_2092788291);

    lv_obj_set_x(ui_comp_get_child(ui_Settingcard3, UI_COMP_SETTINGCARD_LABEL12), 25);
    lv_obj_set_y(ui_comp_get_child(ui_Settingcard3, UI_COMP_SETTINGCARD_LABEL12), 0);
    lv_label_set_text(ui_comp_get_child(ui_Settingcard3, UI_COMP_SETTINGCARD_LABEL12), "About");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_Settingcard3, UI_COMP_SETTINGCARD_LABEL12), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Setting_Page);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 5);
    lv_obj_set_y(ui_Label10, 6);
    lv_label_set_text(ui_Label10, "Setting");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Time display: Hour:Minute (top right) */
    ui_TimeHourLabel = lv_label_create(ui_Setting_Page);
    lv_obj_set_width(ui_TimeHourLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeHourLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeHourLabel, -38);
    lv_obj_set_y(ui_TimeHourLabel, 6);
    lv_obj_set_align(ui_TimeHourLabel, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_TimeHourLabel, "12");
    lv_obj_set_style_text_font(ui_TimeHourLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeColonLabel = lv_label_create(ui_Setting_Page);
    lv_obj_set_width(ui_TimeColonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeColonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeColonLabel, -28);
    lv_obj_set_y(ui_TimeColonLabel, 6);
    lv_obj_set_align(ui_TimeColonLabel, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_TimeColonLabel, ":");
    lv_obj_set_style_text_font(ui_TimeColonLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeMinuteLabel = lv_label_create(ui_Setting_Page);
    lv_obj_set_width(ui_TimeMinuteLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeMinuteLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeMinuteLabel, -5);
    lv_obj_set_y(ui_TimeMinuteLabel, 6);
    lv_obj_set_align(ui_TimeMinuteLabel, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_TimeMinuteLabel, "00");
    lv_obj_set_style_text_font(ui_TimeMinuteLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Settingcard, ui_event_Settingcard_Settingcard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settingcard1, ui_event_Settingcard1_Settingcard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settingcard2, ui_event_Settingcard2_Settingcard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settingcard3, ui_event_Settingcard3_Settingcard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel3, ui_event_Panel3, LV_EVENT_ALL, NULL);

    ui_Setting_PageTimer = lv_timer_create(Setting_Page_timer_cb, 500, NULL);
}

void ui_Setting_Page_deinit(void)
{
    if(ui_Setting_PageTimer != NULL)
    {
        lv_timer_del(ui_Setting_PageTimer);
        ui_Setting_PageTimer = NULL;
    }
    ui_Setting_Page = NULL;
    ui_Panel3 = NULL;
    ui_Settingcard = NULL;
    ui_Settingcard1 = NULL;
    ui_Settingcard2 = NULL;
    ui_Settingcard3 = NULL;
    ui_Label10 = NULL;
    ui_TimeHourLabel = NULL;
    ui_TimeColonLabel = NULL;
    ui_TimeMinuteLabel = NULL;
}
