// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../Inc/ui_Setting_Dis_Bri_Page.h"
#include "../Inc/ui_Setting_Page.h"
#include "../Inc/ui_Brightness_Page.h"
#include "HWDataAccess.h"
#include <stdio.h>
lv_obj_t * ui_Setting_Dis_Bri_Page = NULL;
Page_t Page_Setting_Dis_Bri = {ui_Setting_Dis_Bri_Page_screen_init, ui_Setting_Dis_Bri_Page_deinit, &ui_Setting_Dis_Bri_Page};
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Settingcard8 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Settingcard6 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Roller3 = NULL;
lv_obj_t * ui_Settingcard5 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Time4 = NULL;
uint16_t ui_screen_timeout_seconds = 5;//亮屏时间暂存变量

static lv_timer_t *ui_Setting_Dis_Bri_PageTimer = NULL;
static uint8_t ui_TimeHourValue = 12;
static uint8_t ui_TimeMinuteValue = 0;


/**
  * @brief   Setting_Dis_Bri_page timer callback (500ms period)
  * @param  timer: LVGL timer
  * @retval None
  */
static void Setting_Dis_Bri_Page_timer_cb(lv_timer_t *timer)
{
  char buf[20]; 
  // Time update (every 500ms)
  HW_DateTimeTypeDef DateTime;
  HWInterface.RealTimeClock.GetTimeDate(&DateTime);
  
  if(ui_TimeHourValue != DateTime.Hours||ui_TimeMinuteValue != DateTime.Minutes)
  {
    ui_TimeHourValue = DateTime.Hours;
    ui_TimeMinuteValue = DateTime.Minutes;
    sprintf(buf, "%02d:%02d", ui_TimeHourValue,ui_TimeMinuteValue);
    lv_label_set_text(ui_Time4, buf);
  }
}
// event funtions
void ui_event_Panel4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Page_Back(LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0);
    }
}
//设置亮度
void ui_event_Settingcard8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Page_Load(&Page_Brightness, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0);
    }
}
//设置亮屏时间
void ui_event_Settingcard6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Roller3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);

        /* 读取 Roller 当前选择并存储为秒数 */
        uint16_t idx = lv_roller_get_selected(ui_Roller3);
        const uint16_t vals[] = {5, 10, 20, 30};
        if(idx < (sizeof(vals)/sizeof(vals[0]))) {
            ui_screen_timeout_seconds = vals[idx];
        }

    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Settingcard6, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Label18, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
//抬腕唤醒
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        //(e);
    }
}

// build funtions

void ui_Setting_Dis_Bri_Page_screen_init(void)
{
    ui_Setting_Dis_Bri_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Setting_Dis_Bri_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_Dis_Bri_Page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Setting_Dis_Bri_Page);
    lv_obj_set_width(ui_Panel4, 240);
    lv_obj_set_height(ui_Panel4, 250);
    lv_obj_set_x(ui_Panel4, 1);
    lv_obj_set_y(ui_Panel4, 15);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_Panel4, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settingcard8 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Settingcard8, 220);
    lv_obj_set_height(ui_Settingcard8, 70);
    lv_obj_set_x(ui_Settingcard8, 0);
    lv_obj_set_y(ui_Settingcard8, -80);
    lv_obj_set_align(ui_Settingcard8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Settingcard8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Settingcard8);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label15, "Brightness");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_label_create(ui_Settingcard8);
    lv_label_set_text(ui_Image5, ">");
    lv_obj_set_style_text_font(ui_Image5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Image5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_align(ui_Image5, LV_ALIGN_RIGHT_MID);

    ui_Settingcard6 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Settingcard6, 220);
    lv_obj_set_height(ui_Settingcard6, 70);
    lv_obj_set_x(ui_Settingcard6, 0);
    lv_obj_set_y(ui_Settingcard6, -80);
    lv_obj_set_align(ui_Settingcard6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Settingcard6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settingcard6, lv_color_hex(0xF1EBEB), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Settingcard6, 100, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label18 = lv_label_create(ui_Settingcard6);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label18, "Screen Timeout");
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_label_create(ui_Settingcard6);
    lv_label_set_text(ui_Image7, ">");
    lv_obj_set_style_text_font(ui_Image7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Image7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_align(ui_Image7, LV_ALIGN_RIGHT_MID);

    ui_Roller3 = lv_roller_create(ui_Settingcard6);
    lv_roller_set_options(ui_Roller3, "5S\n10S\n20S\n30S", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Roller3, 73);
    lv_obj_set_width(ui_Roller3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Roller3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Roller3, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Settingcard5 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Settingcard5, 220);
    lv_obj_set_height(ui_Settingcard5, 70);
    lv_obj_set_x(ui_Settingcard5, 0);
    lv_obj_set_y(ui_Settingcard5, -80);
    lv_obj_set_align(ui_Settingcard5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Settingcard5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Settingcard5);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label17, "Wake  Wrist");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Settingcard5);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_RIGHT_MID);

    ui_Label13 = lv_label_create(ui_Setting_Dis_Bri_Page);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 5);
    lv_obj_set_y(ui_Label13, 6);
    lv_label_set_text(ui_Label13, "Display & Brightness");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time4 = lv_label_create(ui_Setting_Dis_Bri_Page);
    lv_obj_set_width(ui_Time4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time4, -5);
    lv_obj_set_y(ui_Time4, 6);
    lv_obj_set_align(ui_Time4, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Time4, "10:00");
    lv_obj_set_style_text_font(ui_Time4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Settingcard8, ui_event_Settingcard8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settingcard6, ui_event_Settingcard6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel4, ui_event_Panel4, LV_EVENT_ALL, NULL);

    ui_Setting_Dis_Bri_PageTimer = lv_timer_create(Setting_Dis_Bri_Page_timer_cb, 500, NULL);
}

void ui_Setting_Dis_Bri_Page_deinit(void)
{
    if(ui_Setting_Dis_Bri_PageTimer != NULL)
    {
        lv_timer_del(ui_Setting_Dis_Bri_PageTimer);
        ui_Setting_Dis_Bri_PageTimer = NULL;
    }
    ui_Setting_Dis_Bri_Page = NULL;
    ui_Panel4 = NULL;
    ui_Settingcard8 = NULL;
    ui_Label15 = NULL;
    ui_Image5 = NULL;
    ui_Settingcard6 = NULL;
    ui_Label18 = NULL;
    ui_Image7 = NULL;
    ui_Roller3 = NULL;
    ui_Settingcard5 = NULL;
    ui_Label17 = NULL;
    ui_Switch1 = NULL;
    ui_Label13 = NULL;
    ui_Time4 = NULL;
}
