// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../Inc/ui_Time_Count_Page.h"
#include "../Inc/ui_Menu_Page.h"
#include "HWDataAccess.h"
#include <stdio.h>
lv_obj_t * ui_Time_Count_Page = NULL;
Page_t Page_Time_Count = {ui_Time_Count_Page_screen_init, ui_Time_Count_Page_deinit, &ui_Time_Count_Page};
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Spinbox1 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Time9 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Button5 = NULL;
static lv_timer_t *ui_Time_Count_PageTimer = NULL;
static uint8_t ui_TimeHourValue = 12;
static uint8_t ui_TimeMinuteValue = 0;
/*ͼƬ*/
LV_IMG_DECLARE(ui_img_307400400);    // assets/��ʼ.png
LV_IMG_DECLARE(ui_img_919959168);    // assets/�ָ�.png
/**
  * @brief   Time_Count page timer callback (500ms period)
  * @param  timer: LVGL timer
  * @retval None
  */
static void Time_Count_Page_timer_cb(lv_timer_t *timer)
{
  char buf[20]; 
  // Time update (every 500ms)
  HW_DateTimeTypeDef DateTime;
  HWInterface.RealTimeClock.GetTimeDate(&DateTime);
  
  if(ui_TimeHourValue != DateTime.Hours||ui_TimeMinuteValue != DateTime.Minutes)
  {
    ui_TimeHourValue = DateTime.Hours;
		ui_TimeMinuteValue = DateTime.Minutes;
    sprintf(buf, "%02d:%02d", ui_TimeHourValue,ui_TimeMinuteValue);
    lv_label_set_text(ui_Time9, buf);
  }

}
// event funtions
void ui_event_Time_Count_Page(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        Page_Back(LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox1, 1);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_Spinbox1, -1);
    }
}

// build funtions

void ui_Time_Count_Page_screen_init(void)
{
    ui_Time_Count_Page = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Time_Count_Page, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Time_Count_Page, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Time_Count_Page);
    lv_obj_set_width(ui_Panel9, 190);
    lv_obj_set_height(ui_Panel9, 37);
    lv_obj_set_x(ui_Panel9, -15);
    lv_obj_set_y(ui_Panel9, -20);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox1 = lv_spinbox_create(ui_Panel9);
    lv_obj_set_width(ui_Spinbox1, 125);
    lv_obj_set_height(ui_Spinbox1, 63);
    lv_obj_set_x(ui_Spinbox1, 30);
    lv_obj_set_y(ui_Spinbox1, 0);
    lv_obj_set_align(ui_Spinbox1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinbox1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_spinbox_set_digit_format(ui_Spinbox1, 4, 2);
    lv_spinbox_set_range(ui_Spinbox1, 0, 9999);
    lv_spinbox_set_pos(ui_Spinbox1, 1 - 1);
    lv_obj_set_style_bg_color(ui_Spinbox1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinbox1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Spinbox1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Spinbox1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Spinbox1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Spinbox1, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinbox1, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -30);
    lv_obj_set_y(ui_Label9, 0);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, ":");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -50);
    lv_obj_set_y(ui_Label3, 1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "0");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Time_Count_Page);
    lv_obj_set_width(ui_Button1, 90);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 60);
    lv_obj_set_y(ui_Button1, 100);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x5AC8FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button1, &ui_img_307400400, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time9 = lv_label_create(ui_Time_Count_Page);
    lv_obj_set_width(ui_Time9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time9, -5);
    lv_obj_set_y(ui_Time9, 6);
    lv_obj_set_align(ui_Time9, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Time9, "10:00");
    lv_obj_set_style_text_font(ui_Time9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Time_Count_Page);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 5);
    lv_obj_set_y(ui_Label14, 6);
    lv_label_set_text(ui_Label14, "Stopwatch");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Time_Count_Page);
    lv_obj_set_width(ui_Button5, 90);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_x(ui_Button5, -60);
    lv_obj_set_y(ui_Button5, 100);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x5AC8FA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button5, &ui_img_919959168, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Time_Count_Page, ui_event_Time_Count_Page, LV_EVENT_ALL, NULL);

    ui_Time_Count_PageTimer = lv_timer_create(Time_Count_Page_timer_cb, 500, NULL);

}

void ui_Time_Count_Page_deinit(void)
{
    if(ui_Time_Count_PageTimer)
    {
        lv_timer_del(ui_Time_Count_PageTimer);
        ui_Time_Count_PageTimer = NULL;
    }
    ui_Time_Count_Page = NULL;
    ui_Panel9 = NULL;
    ui_Spinbox1 = NULL;
    ui_Label9 = NULL;
    ui_Label3 = NULL;
    ui_Button1 = NULL;
    ui_Time9 = NULL;
    ui_Label14 = NULL;
    ui_Button5 = NULL;
}
