// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOME_PAGE_H
#define UI_HOME_PAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "PageManager.h"

// SCREEN: ui_Home_Page
extern Page_t Page_Home;
extern void ui_Home_Page_screen_init(void);
extern void ui_Home_Page_deinit(void);
extern void ui_event_Home_Page(lv_event_t * e);
extern lv_obj_t * ui_Home_Page;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Time1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Bar3;
extern void ui_event_battery7(lv_event_t * e);
extern lv_obj_t * ui_battery7;
extern lv_obj_t * ui_steps;
extern lv_obj_t * ui_Label34;
// CUSTOM VARIABLES
extern lv_obj_t * ui_Date1;
extern lv_obj_t * ui_TimeHourLabel;
extern lv_obj_t * ui_TimeMinuteLabel;
extern lv_obj_t * ui_DateLabel;
// IMAGES AND IMAGE SETS
//LV_IMG_DECLARE(ui_img_2145288589);    // assets/蓝牙.png

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

